### ISSUE TITLE
How can i run the endfront project

### ISSUE THREAD

**Issue by a985987819** [MizzleAa/segment-anything-demo#2]
Excuse me, i'm a frontend new boy.

I noticed that your project is one of the few SAM projects with **well-established front-end examples**.

The official demo is so small that I can only learn a little bit about it.

I want to run your project locally.Would you please tell me how to run the end-front project?

I'm not very familiar with Python and its environment.

And i want to know is it not by clickType to determine whether to add or subtract the mask.

Thanks a lot of you!

**Comment by MizzleAa** [comment]
Version information:

Frontend:

Node.js version: v18.16.0
Backend:

Python version: 3.10.10
Please note that the backend should be set up first, and then you can run the frontend. You can refer to the README files in the respective repositories for detailed instructions.

Here are the links to the repositories:

Backend: https://github.com/MizzleAa/segment-anything-demo-react-fastapi/tree/main/backend
Frontend: https://github.com/MizzleAa/segment-anything-demo-react-fastapi/tree/main/frontend

If you follow the instructions in the README files, you should be able to set up the backend and then run the frontend successfully.

If you have any further questions or need additional assistance, feel free to ask. Happy coding!
